import itertools

"""
the function generate_L: function, that generates all the sentences that can 
exist in the regular set L (Part 2 in project)
"""

def generate_L(max_y=2, max_z=2):
    # these are the abbreviations used in paper

    X = "the woman such that"
    Y = "the man such that"
    she = "she"
    W = "left is here"

    Z_options = [
        "gave him to him",
        "gave him to this",
        "gave this to him",
        "gave this to this"
    ]

    sentences = []

    for y_count in range(max_y + 1):
        y_part = ' '.join([Y] * y_count)

        for z_count in range(max_z + 1):
            for z_sequence in itertools.product(Z_options, repeat=z_count):
                #generate the sentence as L = X Y* she Z* W
                z_part = ' '.join(z_sequence)
                sentence = ' '.join(filter(None, [X, y_part, she, z_part, W]))
                sentences.append(sentence)

    return sentences

# the usage of function
#for s in generate_L(max_y=1, max_z=2):
#    print(s)

"""
the function is_in_A: In any initial segment of the part after "she", the number of 
"this" should never exceed the number of "him" by more than 1.
(part 2 in the project)
"""

def is_in_A(s):
    tokens = s.split() #splitting the string so it's easer to check conditions
    try:
        she_index = tokens.index("she")
    except ValueError:
        return False  # no "she" in sentence

    #counters
    this_count = 0
    him_count = 0

    for word in tokens[she_index + 1:]:
        if word == "this":
            this_count += 1
        elif word == "him":
            him_count += 1

        # check the key condition at every step
        if this_count > him_count + 1:
            return False

    return True

"""
the function filter_L_english_like we filter the strings we need to treat:
1. also generated by generate_L()
2. pass the is_in_A() test 
"""

def filter_L_english_like(max_y=2, max_z=2):
    results = []
    for s in generate_L(max_y, max_z):
        if is_in_A(s):
            results.append(s)
    return results

"""
This function simulates the failure of a context-free grammar (CFG) 
to capture the full complexity of set A.
"""

def simulate_pda_failure(max_y=5, max_z=5):
    failures = []
    #filter those that satisfy is_in_A
    for s in generate_L(max_y, max_z):
        if not is_in_A(s):
            continue  # skip sentences not in A

        # count 'Y' parts

        y_count = s.count("the man such that")

        # count 'Z' parts
        z_count = sum(s.count(phrase) for phrase in [
            "gave him to him",
            "gave him to this",
            "gave this to him",
            "gave this to this"
        ])
        # Mismatch indicates PDA failure — can't track both
        if y_count != z_count:
            failures.append((s, y_count, z_count))

    return failures


"""
demonstrate how it works
"""

print("=== Sentences in L ∩ A (\"English-like\") ===")
accepted = filter_L_english_like(max_y=2, max_z=2)
for s in accepted:
    print("-", s)

print("\n=== CFG Failure Examples (Y ≠ Z despite passing A) ===")
failures = simulate_pda_failure(max_y=5, max_z=5)
for s, y, z in failures:
    print(f"Y count = {y}, Z count = {z}")
    print(s)
    print("---")
